testname: Improving dialogue clarity in BBC programmes
testId: dialogue_enhancement
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to BBC Research and Development's experiment! <br/><br/>Are you ready to be thrilled for almost an hour!?
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: Do you consent to having your brains harvested in the name of science?

