testname: Improving dialogue clarity in BBC programmes
testId: dialogue_enhancement_1
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: You are in group 1<p></p>Thank you for participating in our experiment!<br/><br/>This experiment will take about an hour.<br/><br/>We are going to ask you to rate five slightly different versions of a clip from one of our shows for dialogue clarity. You can take as long as you like on each clip, there will be fifteen in total. You will be asked whether the version is better or worse than a reference clip. The first clip is for practise, to get used to the interface. After the first clip, the experiment will begin.<br/><br/>
    - type: headphones
      content: Hello world
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: Do you consent to having your brains harvested in the name of science?

    - type: mushra
      id: training
      name: How does the speech clarity of each version of the broadcast clip compare to the reference?
      content: <b>This is a training example! Take as long as you like to familiarise yourself with the interface.</b><br></br>In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
      showWaveform: true
      enableLooping: true
      randomize: false
      reference: stimuli/HDM-02-mix.wav
      stimuli:
          C1: stimuli/HDM-02-mix-hf-n.wav
          C2: stimuli/HDM-02-remix-orig-hf-n.wav
          C3: stimuli/HDM-02-remix-bss-htdft-hf-n.wav
          C4: stimuli/HDM-02-remix-bss-cfk-hf-n.wav
    
    -
        - random
        - type: mushra
          id: trial_1_DIP-02
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/DIP-02-mix.wav
          stimuli:
            C1: stimuli/DIP-02-mix-hf-n.wav
            C2: stimuli/DIP-02-remix-orig-hf-n.wav
            C3: stimuli/DIP-02-remix-bss-htdft-hf-n.wav
            C4: stimuli/DIP-02-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_2_DIP-03
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/DIP-03-mix.wav
          stimuli:
            C1: stimuli/DIP-03-mix-hf-n.wav
            C2: stimuli/DIP-03-remix-orig-hf-n.wav
            C3: stimuli/DIP-03-remix-bss-htdft-hf-n.wav
            C4: stimuli/DIP-03-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_3_DIP-04
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/DIP-04-mix.wav
          stimuli:
            C1: stimuli/DIP-04-mix-hf-n.wav
            C2: stimuli/DIP-04-remix-orig-hf-n.wav
            C3: stimuli/DIP-04-remix-bss-htdft-hf-n.wav
            C4: stimuli/DIP-04-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_4_DIP-07
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/DIP-07-mix.wav
          stimuli:
            C1: stimuli/DIP-07-mix-hf-n.wav
            C2: stimuli/DIP-07-remix-orig-hf-n.wav
            C3: stimuli/DIP-07-remix-bss-htdft-hf-n.wav
            C4: stimuli/DIP-07-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_5_HDM-01
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/HDM-01-mix.wav
          stimuli:
            C1: stimuli/HDM-01-mix-hf-n.wav
            C2: stimuli/HDM-01-remix-orig-hf-n.wav
            C3: stimuli/HDM-01-remix-bss-htdft-hf-n.wav
            C4: stimuli/HDM-01-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_6_HDM-05
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/HDM-05-mix.wav
          stimuli:
            C1: stimuli/HDM-05-mix-hf-n.wav
            C2: stimuli/HDM-05-remix-orig-hf-n.wav
            C3: stimuli/HDM-05-remix-bss-htdft-hf-n.wav
            C4: stimuli/HDM-05-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_7_HDM-08
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/HDM-08-mix.wav
          stimuli:
            C1: stimuli/HDM-08-mix-hf-n.wav
            C2: stimuli/HDM-08-remix-orig-hf-n.wav
            C3: stimuli/HDM-08-remix-bss-htdft-hf-n.wav
            C4: stimuli/HDM-08-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_8_HDM-09
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/HDM-09-mix.wav
          stimuli:
            C1: stimuli/HDM-09-mix-hf-n.wav
            C2: stimuli/HDM-09-remix-orig-hf-n.wav
            C3: stimuli/HDM-09-remix-bss-htdft-hf-n.wav
            C4: stimuli/HDM-09-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_9_HDM-10
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/HDM-10-mix.wav
          stimuli:
            C1: stimuli/HDM-10-mix-hf-n.wav
            C2: stimuli/HDM-10-remix-orig-hf-n.wav
            C3: stimuli/HDM-10-remix-bss-htdft-hf-n.wav
            C4: stimuli/HDM-10-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_10_HDM-11
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/HDM-11-mix.wav
          stimuli:
            C1: stimuli/HDM-11-mix-hf-n.wav
            C2: stimuli/HDM-11-remix-orig-hf-n.wav
            C3: stimuli/HDM-11-remix-bss-htdft-hf-n.wav
            C4: stimuli/HDM-11-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_11_SASRH-02
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/SASRH-02-mix.wav
          stimuli:
            C1: stimuli/SASRH-02-mix-hf-n.wav
            C2: stimuli/SASRH-02-remix-orig-hf-n.wav
            C3: stimuli/SASRH-02-remix-bss-htdft-hf-n.wav
            C4: stimuli/SASRH-02-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_12_SASRH-05
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/SASRH-05-mix.wav
          stimuli:
            C1: stimuli/SASRH-05-mix-hf-n.wav
            C2: stimuli/SASRH-05-remix-orig-hf-n.wav
            C3: stimuli/SASRH-05-remix-bss-htdft-hf-n.wav
            C4: stimuli/SASRH-05-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_13_SASRH-08
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/SASRH-08-mix.wav
          stimuli:
            C1: stimuli/SASRH-08-mix-hf-n.wav
            C2: stimuli/SASRH-08-remix-orig-hf-n.wav
            C3: stimuli/SASRH-08-remix-bss-htdft-hf-n.wav
            C4: stimuli/SASRH-08-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_14_SASRH-10
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/SASRH-10-mix.wav
          stimuli:
            C1: stimuli/SASRH-10-mix-hf-n.wav
            C2: stimuli/SASRH-10-remix-orig-hf-n.wav
            C3: stimuli/SASRH-10-remix-bss-htdft-hf-n.wav
            C4: stimuli/SASRH-10-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_15_SASRH-11
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/SASRH-11-mix.wav
          stimuli:
            C1: stimuli/SASRH-11-mix-hf-n.wav
            C2: stimuli/SASRH-11-remix-orig-hf-n.wav
            C3: stimuli/SASRH-11-remix-bss-htdft-hf-n.wav
            C4: stimuli/SASRH-11-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
        - type: mushra
          id: trial_16_SASRH-13
          name: How does the speech clarity of each version of the broadcast clip compare to the reference?
          content: In each vertical column is a different version of a clip from a BBC programme. For this programme clip, please rank each dialogue clarity of each version against the reference clip, avoiding comparing the versions to eachother. You can listen to each clip and version as many times as you like, and choose to loop a part of it to focus on a shorter section of the clip. 
          reference: stimuli/SASRH-13-mix.wav
          stimuli:
            C1: stimuli/SASRH-13-mix-hf-n.wav
            C2: stimuli/SASRH-13-remix-orig-hf-n.wav
            C3: stimuli/SASRH-13-remix-bss-htdft-hf-n.wav
            C4: stimuli/SASRH-13-remix-bss-cfk-hf-n.wav
          enableLooping: true
          randomize: true
    
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
        - type: number
          label: Age
          name: age
          min: 0
          max: 100
          default: 30
        - type : likert
          label :  Are you a hearing aid user?
          response:
            - value: 1
              label: Yes
            - value: 0
              label: No
        - type: text
          label: Gender
          name: gender
        - type: text
          label: Email (optional)
          name: mail
