testname: Improving dialogue clarity in BBC programmes
testId: dialogue_enhancement
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to BBC Research and Development's experiment! <br/><br/>Are you ready to be thrilled for almost an hour!?
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: Do you consent to having your brains harvested in the name of science?


    - type: mushra
      id: training
      name: MUSHRA
      content: Training example
      showWaveform: true
      enableLooping: true
      randomize: false
      reference: stimuli/HDM-02-mix.wav
      stimuli:
          C1: stimuli/HDM-02-mix-hf-n.wav
          C2: stimuli/HDM-02-remix-orig-hf-n.wav
          C3: stimuli/HDM-02-remix-bss-htdft-hf-n.wav
          C4: stimuli/HDM-02-remix-bss-cfk-hf-n.wav
    -
      - random
      - type: mushra
        id: trial_1_DIP-02
        name: Clip 1
        content: How does the speech clarity of these clips compare to the reference clip?
        reference: stimuli/DIP-02-mix.wav
        stimuli:
            C1: stimuli/DIP-02-mix-hf-n.wav
            C2: stimuli/DIP-02-remix-orig-hf-n.wav
            C3: stimuli/DIP-02-remix-bss-htdft-hf-n.wav
            C4: stimuli/DIP-02-remix-bss-cfk-hf-n.wav
        enableLooping: true
        randomize: true

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:

          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type : likert
            label :  Are you a hearing aid user?
            response:
             - value: 1
               label: Yes
             - value: 0
               label: No
          - type: text
            label: Gender
            name: gender
          - type: text
            label: Email (optional)
            name: mail
