testname: NOT a MUSHRA
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    # - type: generic
    #   id: first_page
    #   name: Welcome
    #   content: Welcome to webMUSHRA!
    # - type: consent
    #   id: consent_page
    #   name: Consent
    #   mustConsent: true
    #   content: Do you consent to having your brains harvested in the name of science?

    - type: mushra
      id: trial1
      name: MUSHRA
      content: Training example
      showWaveform: true
      enableLooping: true
      randomize: false
      reference: stimuli/A.wav
      stimuli:
          C1: stimuli/B.wav
          C2: stimuli/C.wav
          C3: stimuli/D.wav
          C4: stimuli/E.wav

    # -
    #   - random
    #   - type: mushra
    #     id: trial_random_1
    #     name: Clip 1
    #     content: How does the speech clarity of these clips compare to the reference clip?
    #     reference: stimuli/A.wav
    #     stimuli:
    #         C1: stimuli/B.wav
    #         C2: stimuli/C.wav
    #         C3: stimuli/D.wav
    #         C4: stimuli/E.wav
    #     enableLooping: true
    #     randomize: true

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:

          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type : likert
            label :  Are you a hearing aid user?
            response:
             - value: 1
               label: Yes
             - value: 0
               label: No
          - type: text
            label: Gender
            name: gender
          - type: text
            label: Email (optional)
            name: mail
