testname: webMUSHRA Example
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to webMUSHRA for Catalan TTS!       
    - type: bs1116
      id: trial1
      name: MUSHRA
      content: This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/continue_2/pol_4.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/finetune_from_cv/pol_4.wav
          C2: configs/resources/audio/narrawoband/pol_4.wav
    - 
          - random
          - type: bs1116
            id: trial_random_1
            name: MUSHRA - Random 2
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/continue_2/pol_5.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/finetune_from_cv/pol_5.wav
                C2: configs/resources/audio/narrawoband/pol_5.wav 
          - type: bs1116
            id: trial_random_1
            name: MUSHRA - Random 2
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/continue_2/pol_6.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/finetune_from_cv/pol_6.wav
                C2: configs/resources/audio/narrawoband/pol_6.wav         
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
